name: app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  font_awesome_flutter: ^10.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  postgres: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/logo.png
  fonts:
      - family: Poppins
        fonts:
          - asset: lib/assets/fonts/Poppins-Black.ttf
            weight: 900
          - asset: lib/assets/fonts/Poppins-BlackItalic.ttf
            weight: 900
            style: italic
          - asset: lib/assets/fonts/Poppins-Bold.ttf
            weight: 700
          - asset: lib/assets/fonts/Poppins-BoldItalic.ttf
            weight: 700
            style: italic
          - asset: lib/assets/fonts/Poppins-ExtraBold.ttf
            weight: 800
          - asset: lib/assets/fonts/Poppins-ExtraBoldItalic.ttf
            weight: 800
            style: italic
          - asset: lib/assets/fonts/Poppins-ExtraLight.ttf
            weight: 200
          - asset: lib/assets/fonts/Poppins-ExtraLightItalic.ttf
            weight: 200
            style: italic
          - asset: lib/assets/fonts/Poppins-Italic.ttf
            style: italic
          - asset: lib/assets/fonts/Poppins-Light.ttf
            weight: 300
          - asset: lib/assets/fonts/Poppins-LightItalic.ttf
            weight: 300
            style: italic
          - asset: lib/assets/fonts/Poppins-Medium.ttf
            weight: 500
          - asset: lib/assets/fonts/Poppins-MediumItalic.ttf
            weight: 500
            style: italic
          - asset: lib/assets/fonts/Poppins-Regular.ttf
          - asset: lib/assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: lib/assets/fonts/Poppins-SemiBoldItalic.ttf
            weight: 600
            style: italic
          - asset: lib/assets/fonts/Poppins-Thin.ttf
            weight: 100
          - asset: lib/assets/fonts/Poppins-ThinItalic.ttf
            weight: 100
            style: italic
